---
title: 谣言动力学
date: 2013-03-09
slug: rumor
---

信息熵公式：

$$h=\sum{-p \cdot logp}$$ 

p是可能性或发生概率的期望

关注度公式：

$$a=\alpha \cdot \Delta p$$ 

a是关注度 $\alpha$是未知参数 $\Delta p$是信息可能性与期望可能性的差 

当$\Delta p$超过阈值$a0$ $a=0$

# 解释 
- 每个人对事情发生的可能性的信心与改变可能性的信心取决于个人经验与理性

- 一件事发生的概率越大 信息价值越小 同时 发生概率越小 信息价值越大 

- 信息熵在信息的固有概率处最大 可能性在固有概率处最高 熵自发取最大值  

- 信息量大的信息可通过联合信息量小的信息来提高可能性 使信息熵回归固有概率

- 关注度与偏离信息固有概率的程度在阈值下成正比 超过阈值迅速降低 阈值因人而异

- 人的关注度不会长期较高 最终选择拒绝或接受新信息 生活恢复正常（进化？）

# 谣言 

- 谣言的特点 可能性小 信息价值大 信息本身指代面广有传播价值

- 辟谣的特点 使谣言信息量降低 发生可能性增大

- 传谣的特点 传播者相信固有概率已经改变或有意改变固有概率  传播就是信息的自发熵增到新固有概率的过程 当固有概率完全改变 谣言就是事实 传谣就是传递新知

- 辟谣不如传谣 人们对可能性小的事感兴趣 可能性大的事熟视无睹 只要偏离固有概率不太离谱 关注度都会很高

- 谣言传不长 总有人对某些事的固有概率有充足的信心 选择性忽视 信息量高的信息会伴随人们对某些事固有概率的改变而不再偏离固有概率 关注度下降 生活恢复正常

- 谣言的改编 通过加入可能性高的信息 如文献 权威（固有概率高）降低信息熵 让固有概率偏的不大 轻微改变固有概率 生活很快恢复正常 反而有利传播

- ''优秀''的谣言 结论偏离固有概率很多 但模糊的补充信息缩小了差距使人更易接受与传播

# 举例 

- 我今天吃饭了- 这是废话 因为正常人每天都吃饭 信息量小 

- 我今天没吃饭- 可能性小于前者 信息量增加 接下来可通过如减肥 没钱等补充信息来提高可能性 使其回归到固有概率 

- 我从来没吃过饭- 可能性很小 信息量大 无法补充信息 概率无法回归且超过阈值 关注度先高后低 认为我骗人 一切得到解释 生活恢复正常 指代面小 没有传播价值

- 人可以不吃饭- 可能性很小 信息量大 可适量补充信息（如科学研究 统计结论）来解释 指代面大 有传播价值 标题党式谣言