---
title: 环境化学的组队原则
author: ''
date: '2017-04-21'
slug: es-team
categories: []
tags: []
---

最近同组两个博后都拿到了教职，聊天时就说到了自己建课题组所需要的人员组成。因为当前课题组的研究方向是分析化学，所以一般至少会需要仪器仿真方向、材料合成方向、数据处理方向与特定应用方向的人才。如果是课题组长，这四方面至少要会两到三项，不然很多项目根本做不起来。回过头来想想，环境化学其实也可以考虑下组队问题。

## 平台

环境化学目标污染物常规一点的大概就是无机方面的重金属与有机方面的农残、食品添加剂、POPs名单上那一坨、PPCPs还有一些生物毒素。往前沿看基本都是非目的检测或筛选，简单一点的是已知污染物的代谢产物与结构类似物，复杂一点就是效应诱导分析或通过QSPR预测毒性这类。这些主题比较热门，如果是环境调查方向，可以各种污染物排列组合去发，毕竟考虑三间分布的话，时间地点人群不同，迁移转化规律也不一样。同时还有非生物介质、生物介质等等污染物载体的差异，研究视角不同，看到的东西也不一样。

从分析技术上看，首先得有前处理设备。常规的超声、ASE、SPE、旋蒸、氮吹、离心机等得有，如果是作方法学的，什么SPME、整体柱、分子印迹、微流控、离子液体、纳米颗粒负载修饰等技术得有会的人，特别纳米材料那一块，考虑上磁性容易做出体系，当然实用性另当别论。这些设备与技术能让你萃取净化到目标物，当然你做无机搞微波消解然后赶酸啥的当我没说，你们那不叫前处理。

处理完了的东西就要检测，环境分析检出限都是ppb级及以下，有机的就别来掺和了。无机检测ICP-MS是一站式解决方案，你要有钱搞得起MC-ICP-MS还可以做无机同位素分析，前提是有钱。有机一般就是质谱了，获取你比较关心核磁红外紫外，但那个出的结果大概率被审稿人鄙视。不过核磁另当别论，关键环境污染物含量太低，一般满足不了核磁要求，如果你能找到做合成的人帮你鉴定未知物那最好不过。质谱里面有条件上obitrap就上，再不济也得有个tof，如果你有FT，那基本可以抛弃前面的色谱了。定量的话qqq跟单杆最好都有，离子阱如果不做便携质谱或是普渡厨子的门生就不要考虑了。电离源也要配齐，气谱EI跟CI，液谱ESI跟APCI，冷门点的双喷雾或DESI也可以搞搞，不然有些污染物你可能根本就测不到。光谱也是一个思路，不过你得往高通量或可视检测去做，发不出文章也可以出点专利产品，这部分一般思路就是做抗体或者化学发光、荧光啥的，主要就是原子分子光谱，不过跟质谱比最大的优势可能就是便宜了。此外，表面共振拉曼光谱也是个快速发文章的渠道，配合一些稀奇古怪的修饰，总能在现场分析上找到突破口。光谱其实也有个大杀器，光源，前提你约的上，高能射线下能对很多过程进行细致分析与成像。此外，元素分析、各类显微镜电镜还有生物方向的特异性分析、测序跟芯片技术在环境领域也有应用，就看你想回答的科学问题是什么了。

上面扯半天主要就是说得有个仪器平台可以依赖，而且多半你也不会买维修合同，这说明初期得有点当金工、电工甚至木工的手艺，没有也没关系，好的平台一般都标配。我现在组里那几台质谱基本都是老板各种谈判低价搞过来的，不是二手demo机就是根本已经坏了，故障五花八门全是自己修，搞得这边博士生毕业都可以去培训仪器公司工程师了，反正多数上门工程师的顶级秘籍就是换件。

## 人才

仪器只会报数，只有人才能把数据变成论文。在这一点上，一个课题组至少要有一个人有数理统计与编程技术背景，甚至每个组员都要有应用层次的编程技术。这可不是说看到别人用了pca，你也用pca去照猫画虎，你至少要知道这些技术为什么用，什么时候用，怎么用。只有这样写论文时才知道你在干什么而不是只知道套模版怎么做。软件工具python、r或matlab都可以。此外，也要有一个工科背景的员工或博后，懂仿真。统计模型与仿真模型完全是两个概念，一个面对数据归纳，一个面对实物或系统用规律演绎；一个用回归，一个各种偏微分方程；一个做假设检验，一个直接在虚拟空间进行实验。小到模拟一个吸附解吸过程，大到生态系统的物质能量循环，仿真模型与统计模型是要相辅相成的。软件工具comsol、matlab甚至netlogo都可以。这两类人是基础人才，能把数据变成故事。

但作为独立课题组只有基础人才是不够的，课题组长一般都有一技之长。环境化学最容易耦合的学科是毒理学、污染控制与环境暴露。毒理学上的人才要对污染物致毒的分子机制玩的转，懂得基因修饰去验证被污染物影响的生物学过程，当然偷懒一点搞点QSPR研究下分子蛋白相互作用机制也是可以的，不过你得真的搞得明白从分子动力学到DFT那一系列的坑，你搞不明白没关系，別坑学生。当然，现代毒理学里急性慢性毒性实验、行为学表征还有流式细胞术什么的基本每篇文章都是标配，不是你的长处也别成为短处。更深入的组学技术如果不是基础够强，花钱找公司做，但数据分析要自己来，很多公司的数据处理技术还停在上个世纪。如果你是污染控制方向，污染物的降解热力学动力学自然要了解吧，拿个mopac算算前线轨道能也可以编出个不错的故事。如果你跑去做工艺养污泥颗粒，那目前似乎没点基因芯片也说不清楚降解机理了。如果你是大气环境化学方向，额，你似乎兼顾有点催化背景好一点。如果是土壤，怎么说也淋过土柱玩过同位素标记吧。如果你搞了个环境暴露方向，最好认识医院里那些缺论文升职称的大夫，随便搞点病人与健康人的样品测下污染物浓度就可能有不错的发现。如果你是公卫那边转过来的，搞点暴露组学配合流行病学研究会有不错的故事。如果你气象那边过来的，搞点气候变化对污染物迁移转化规律的影响也会不错。总之课题组长要会找到研究切入点与生态位，跟风怎么也要等你手头有资源再说，早期做出特色更重要。

说了这么多你会发现现在要想做出点名堂多半是要靠合作的，很多技能不可能同时出现在一个人身上，多数课题组也一般只会关注到一个方向，但如果科学问题的解决需要多角度切入说明，那就拿出诚意去找合作者。环境科学本身就是面向问题出发的，而阐述问题的证据角度越多，结论越靠谱。同时，要不断从基础学科的理论与技术进展中汲取营养，一个学科里聪明人多，那么新思想出的就多，这些思想不仅可以解决这个学科里的问题，也可以解决其他学科的问题。在这一点上，物理、化学与生物的技术进展与计算机科学、统计还有数学的理论思想都值得关注。在那些聪明人比较多的学科里的人也可以搞个跨界，大家共同发展。这里面最明显的就是计算机科学对生物信息学与金融的带动，往往一个学科的进步暗含了其他学科进步的契机。如果你打算做点学术事业，到聪明人最多的学科里去学习，然后回自己的学科里发展。这里面最大的问题就是，一般聪明人多的学科工资要比不那么多的学科高，这时候就得把学术理想当鸡血用了。

## 合作

有两种做事态度，一种是做所有事都是从自己需求的出发，追求个人的功成名就，科研成果是垫脚石；另一种是从解决问题的需求出发，解决问题是唯一目标，个人名利是副产品。据我观察，两种态度都不影响个人成长与学科进步或退步，但后一种生活态度的人想的少一点，幸福指数要高一点。我个人喜欢面向问题解决问题，当然这个态度会让你不断得罪人你自己还意识不到，不过整体大脑负担小，睡得香。如果面向问题，一作可以不强求、首先发现也可以不要但问题要说明白与说清楚，把好的思想传播出去而不是跟宝贝一样藏着掖着，太阳底下没有新鲜事。这个态度另一个好处就是容易促成合作，如果合作可以成功就比各干各的的社会效益或学科贡献更多。

很多人都知道囚徒困境里一个比较好的策略就是以牙还牙，但其实这个策略只是可以保证整体收益为零，如果想为正，最好的方法就是双方不断合作。以往的思路都是构建在把自己的课题组搞成巨无霸，目前国内主流就是如此，这样内部合作强于外部合作，容易稳定学术界地位，从这个角度看巨无霸课题组是可取的，我读博的中科院主流基本如此，配合良好的顶层设计可以攻坚克难。但目前来看，如果是一个新课题组长，这样搞一是根本就没那么多资源，二是新人初期很难招到理想的同事。所以此时的优势策略不应该依附大课题组，而应该是跟同龄人合作，在平等的基础上共同成长，面向问题解决问题。不要担心自己的技术被别人学走，别人学走正是说明这个技术有价值，没人学才是大问题。另外，早期技术跟别人合作推广了，你还可以开发新技术嘛，我从未见过有课题组靠一项保密技术可以维持30年的，而对于正常科研人员，30年差不多也该给后辈挪窝了。

合作是没必要在办公室发生的，很多问题或思路有时候就是差一句话。印象中有公司就通过设计让员工的午餐排队时间控制在3～4分钟左右好让排队时员工能多交流，时间长了员工就出去吃，少了讨论不充分。合作甚至不用物理接触，现在实时通讯工具一大把，随时都可以交流。不过，搞成微信群那样就太花哨，也容易被朋友圈跟红包分散精力，用邮件列表功能又太单一，目前我组内用slack。一方面可以实时交流，另一方面通过区分频道可以针对主题或项目进行讨论协作，此外也可以作为个人项目管理与点对点交流工具。

我猜的不错的话多数人看到这里也就停了，因为周围可能没有人用，不过万事都有个开头，我已经建立了一个slack主页：yufree.slack.com，欢迎大家给我发邮件slack at yufree.cn拿邀请尝试，不建议留邮箱，原因你懂的。可以当作一个即时交流组队平台的实验品，相互学习，共同进步。