---
title: 社会感知、文献解读与棋盘思考
author: ''
date: '2017-05-06'
slug: social-sense
categories: []
tags: []
---

## 社会感知

最近看到一篇[综述](http://journals.lww.com/co-allergy/Fulltext/2017/04000/Social_media_use_for_occupational_lung_disease.4.aspx)，大意介绍了下通过社交网络数据来进行职业性肺病的研究趋势。其实回想一下，从大概四五年前就开始有利用类似数据进行研究的报导了，甚至还有个相关名词：社会感知。

字面理解，社会感知通过收集社会群体传感数据来研究社会中群体行为或相关科学问题。例如，我收集医院呼吸科就诊数据，然后看看这一观察点是否与其他环境因素或个体遗传因素有关联，譬如有人会[发现](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0153099)雾霾严重时呼吸科就诊率会上升。但其实研究可以不局限于特定行业，社交网络的快速发展一方面成为很多人日常生活的必需品，另一方面也提供了大量信息输出。例如有人就[研究](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2835988)过在重度空气污染时人们会在微博上的讨论行为。同样的主题似乎在地理学研究中用到，我曾听过一个报告使用的就是微博签到数据来观察旅游旺季游客的聚集行为。如果不局限在国内，实际各大不存在的社交网站都发表过类似论文，有的是基于地理信息，有的是基于语义分析，还有的则基于传播结构用图论的方法去研究。

总的来说，社会感知可以看作一个研究手段或视角，其应用面还可以更大。就环境分析而言，污染物调查类论文往往侧重于研究其在环境介质中的迁移转化规律，但逻辑上看，污染物的产生多半是人类行为，也就是说迁移转化规律也可能从社会感知角度去考察。例如我们可以关注一些污染企业的经济指标，其波动很有可能与污染物的环境浓度产生关联，如果是滞后性关联，我们是可以预测一些污染的集中爆发的。同样，人们在社交网络里关注的污染物是存在新闻传播高峰的，也就是脉冲式的，但污染物浓度的变化一般是连续的，这之间的差异或趋势可以用来区别环境污染的生理影响与心理影响。如果环境科研工作者不尽快掌握相关研究手段，那么不出意外做社会学研究或计算机科学研究的人会渗透过来。

最近掌握相关数据的公司纷纷成立研究院，人员组成学科背景都比较多样，很有可能比学术界优先发现有意思的现象。相比之下，学术界学科间壁垒还比较明显，很有可能因为研究手段的落后而走下坡路，而且业界科研的待遇在国外是普遍高于起步期学界待遇的，而人才的流动一般都会是往前沿去，如果在业界那就会流向业界。现在的研究视角越来越多样化与面向问题出发，单一学科或视角、固定的研究模版与闭塞的交流很容易快速衰落而不自知。例如当前大家都喜欢投学科顶尖期刊，很多老牌期刊却存在门户之见，对新方向把握不充分，新研究无法在原有学科体系内成长就会到其他领域或开辟领域野蛮生长，很多人看不上眼的 plos one 跟 scientific report 等新综合性期刊在慢慢孕育新学科。从引用量上可能不明显，但媒体曝光度上来说，新的研究方向更高。如果所有科研经费总量不变，新学科趋势通过媒体影响力会去逐渐挤占传统学科的资源，届时可能会出现系统性学科衰落。这就好比科学共同体的新陈代谢，缓慢却不可逆。所有学科都曾是新学科，也将会成为传统学科，如果内部不能换血，那就只能等外部输血了。这里血指的就是类似社会感知这样的前沿趋势与视角，这对起步期科研人员尤其重要，因为一旦搞错形势，后面不论你多努力可能都会有一种听天由命的焦虑感。

## 文献解读

最近几年，科普类网站或公众号的快速崛起促进了科学传播，越来越多的人愿意去把最前沿的研究发现带给有好奇心的听众，特别是目前正在进行科研工作的研究生与老师。但我发现很多人在进行解读时并没有很好的说明白研究类型而更多去讨论发现的事实与意义，这样会形成一些误解。

### 没有研究基线的盲信

很少有研究是凭空蹦出来的，但对科学报道的受众而言，绝大多数都是头一回听到一些研究领域。也就是说听众都是白纸一张，你说什么他们会首先接纳为事实而不是批判思考，因为多半根本就没有提供批判思考的知识体系。所以文献解读很重要的一点就是要说明我们之前对这个问题了解到什么程度了，有一个基线与背景可以让读者去展开批判思考而不是全盘接受。由于很多论文解读出自领域内专家，而专家通常喜欢用复杂术语树立权威感，所以这个偏误多半只能读者自己揣度，留有余地。

### 现象与规律分不清

社会科学方面的研究论文解读时经常出现，论文描述的是当前现象，但解读时进行了规律演绎。例如队列研究发现富人们存在早期打高尔夫球的共同喜好，这是一个现象，不能解读成当前你去打高尔夫球，以后就可能变成富人。现象与规律分不清不能用简单的相关不代表因果来解释，更深层次的问题在于，即便很多现象说明的因果关系是事实存在的，时过境迁后，这个因果关系解除了。同样是上面的例子，也许早期打高尔夫球其实是因为能在高尔夫球场获取更好的人脉，但如果现在富人们主要社交方式变成打壁球，那么这个现象只能描述为历史事件，曾经是合理的，但当前完全不合理了。规律是相对稳定不变的而现象是历史性的，一般读者看论文解读的视角是规律视角而不是现象视角，如果解读者自己没搞清楚，那就很容易产生误导。多数科学发现都是有语境的，语境就是适用范围，也可理解为历史条件下的现象。而放之四海而皆准的规律是可遇不可求的，特别社会科学里存在舆论反馈与行为习惯的转变，很多结论在自然态下成立在社会系统中就面目全非了，整个社会到处都是局部最优解与区域护城河，不能当成均相系统研究。

### 决策风险

要知道很多人的决策，特别在健康、育儿与理财等切身相关的主题决策上是很依赖专家意见的，一旦误导后果都是自负的。烟盒上都标个吸烟有害健康，论文解读上最好也提升下决策风险。不知道从什么时候开始，很多原来自然而然的事都出现了各种专业人士去提供服务并帮助决策，所有人都变成了决策困难者。就育儿而言，当前最新的研究成果与30年前父母自己摸索的育儿经验究竟能造成多大的差异，我想这也是个摸石头过河的事。但解读研究成果的人往往并不提示风险，直接论述方法与成效。从读者角度，这个风险往往会被期刊的权威性所掩饰，但事实上越是影响力大的期刊，撤稿率越高；越是前沿的发现，越有可能是缺少证据的。如果论文解读最终变成了个人经验的论述，那么读者应该放弃其决策价值，不然跟信教没啥区别。

关于文献解读甚至其他种类的文章，读的时候最好也要有点类似社会感知的想法，想想看这是不是现象唯一的解释与思考视角？解读者有没有夹藏私货？自己有没有意识到其中的偏误与决策风险？

## 棋盘思考

上面关于文献解读的分析实际上也只是棋盘思考的一个应用。设想你跟我下棋，如果你下你的，我下我的那就没意思了，一般情况双方都会去思考对方的立场与策略。好比你去考试，如果你身经百战，那么你一定掌握了出题人视角与阅卷人视角，出题人考察你对某个问题的理解而阅卷人关注的是得分点，作为答题者最好就是把答案分条，展示你理解了某个知识点。其实出题人与阅卷人也会意识到答题者的应对策略去制定答案，这样最后真正懂问题的人总会高分通过，而一知半解的人很难蒙混过关。而在互联网上看信息或报道，你至少要意识到一个三方对弈场景。

所有报道都存在一个事实基础，把事实展示给你的人是第二方，第三方就是你。大多数人并不能意识到事实与展示事实的人之间的互动关系而看成一体，但其实立场差异不同。A采访了B，B所叙述的事实经过A的加工往往会产生微妙的情感共鸣与调动，而受众就是C。C永远只看到A笔下的B，甚至B是否存在C都不会去怀疑。C当然可以自主采访B，但同样C在描述时也是带有某些情感共鸣的。想到这一点，所有报道，包括自己所提供的，对于别人都是相对主观的。也就是说，棋盘思考的核心不在于了解对方想的是什么，而是意识到自己的局限性。

只有知道自己的局限性，才能对别人的局限性进行合理评估并达成一定程度上的信任或不信任。这始终都是个决策问题，只是日常生活中发生的太过频繁，很多人意识不到其中发生的过程，总是跟着感觉走。但其实跟着感觉走可能也是一种良好的决策，只是在行为经济学大行其道的今天，总有商人盯着你的行为，考虑能否从中挖到一桶金。无论如何，现代社会实在是错综复杂，所有人都在犯错或试错，站在承认局限性的位置思考总不会错的太离谱。