---
title: 社会动物、利率与三间分布
author: ''
date: '2017-04-08'
slug: rates
categories: []
tags: []
---

## 社会动物

这周读完了戴维·布鲁克斯的《社会动物》，这本书很特殊，一方面你可以把它当非虚构类来读，因为里面综合了大量社会学、经济学、心理学甚至脑科学的研究成果，但另一方面却又可以看作一个虚构类的小说，因为所有研究成果都贯穿于一对夫妻的成长过程，从其父母的相识相爱、童年、青少年、大学、创业、职场成长、中年危机、事业巅峰贯穿到退休后的生活与男主角的死亡，作者将全过程娓娓道来，娴熟地把研究成果、社会现象与生活经验体会捏合到一个时间尺度之中，阅读体验非常好。同类的书还有《苏菲的世界》，不过那个是将哲学的，如果你对经济学感兴趣，《狼与香辛料》这部轻小说也是类似的结构，读这类书不必执着于对错与严谨性，沉浸于故事中就好。

但读这本书我最大的体验就是作者观点其实跟另一本去年读过的《贪婪的大脑》是有一定冲突的。《社会动物》的作者戴维·布鲁克斯是芝加哥大学历史学专业毕业的，目前是一位专栏作家兼政治评论员，其背景类似男主角哈罗德。《贪婪的大脑》的作者丹尼尔·博尔则是一位神经科学家，论述风格带有明显的理工类论文的节奏。这种迥然不同的背景似乎也影响了其文章思想的体现。《社会动物》中，女主角埃丽卡创立了一家以引入各种行为经济学研究成果来帮助企业发展的咨询公司，但是那些拎着核磁共振仪的神经科学家却更受企业欢迎，这导致创业初期并不顺利。这影射了目前两种咨询策略，一种是诉诸非理性或潜意识的研究而另一种则是理性量化的实验性科学。严格说这并不对立，但在《贪婪的大脑》中，丹尼尔·博尔认为很多关于无意识起作用的研究实质上并没有回答原始问题而仅仅是忽略或混淆了某些过程中意识与自我意识的区别与作用方式，因而埃丽卡的成果或许有用，但并不是一个正确的解释。然而戴维·布鲁克斯却认为过分依赖理性的力量也存在严重的缺陷，那就是在这类研究中过分依赖有良好效果的理性主义与模式的识别，人的社会性等难以量化分析的成分都被系统性地忽略了，而社会属性才是解决当前社会问题的关键。具体来说就是为什么社会学研究精彩纷呈，但落实到政策上总是答非所问，似乎理性的策略设计总是在社会层面不成功，例如美国教育改革与税收政策并没有实现原有的目标，反而不断激化了社会矛盾与割裂。

这是一个有意思的对比，《社会动物》中，戴维·布鲁克斯对社会各阶层的运转、教育系统及政治运作有着近乎调侃的洞见，例如描述社会中上层人生活方式时会说他们“选购耐用品时无比奢侈，而购买消耗品时则能省则省”、“政治演说的结构非常简单：前12分钟讲你，后12分钟讲我”、“管理国家的才能不可避免地等同于掌控心灵的才能”……这本书开头就定了一个基调，那就是“痛苦是通往智慧的必经之路”，文中的调侃与故事发展也印证了这一点。反观由科学家写作的《贪婪的大脑》，虽然同样涉及了意识、潜意识与冥想等主题，但确实少了很多人性化的东西，虽然结论类似。然而，在《贪婪的大脑》中，结论的描述经常是符合科学原则的去限定范围与保留疑问空间，而《社会动物》中你就会发现很多论断式的对研究结果的引用，掷地有声但拒绝了进一步地讨论，作为观点的陈述无可厚非，但过于绝对。例如对于是否存在自由意志的问题，《贪婪的大脑》认为如果我们接受人脑是机器的或者说一元论的，那么自由意志确实不该认为是存在的，然而大脑的复杂性却保留了产生自由意志的可能，而且作者讨论了关于自由意志问题上存在的定义问题。在《社会动物》里，却常常出现“行为的改变往往先于态度和感情的改变”等共识性论断而缺乏得出结论的细节与背后争论的讨论，这可以看作文科背景人的短板，如果其更深刻理解科研中的不确定性，可能会更真实描述问题。但这却是一种常见的写作手法，可以理解为liberate art中核心技艺，我疑心调和这种科学理性与感性表达的尝试是徒劳的。科学家总应该读点哲学与人文的东西来理解社会运转，而社会学者则急需科学哲学与科研思维的训练来搞清楚探求真相的过程，不要过度延伸。

不过，确实应该重视《社会动物》中提到的问题，特别是情感共鸣、群体孤独与社会信任感的缺失等问题。戴维·布鲁克斯给出的药方是教育与有限权利政府，着力于修复认知负荷加剧的现代社会中社会流动性问题，解决多元化社会中的伦理困境。虽然作者指向的是美国社会的问题，但其实是个全球面对的难题：如何让所有人都切实感受到幸福而不是割裂与分离。也许戴维·布鲁克斯的另一本书《品格之路》从历史人物的成长过程角度探讨了这个问题并给出了个人层次的解决方案，不过我没读过，不好评论。

## 利率

《社会动物》中，虚构的男女主人公虽然经历了一生，但其实时间是相对静止的。所有阶段都像是从当前社会抽离出一个年龄段的人来进行分析，这样做丰富了当前，但历史没有被考虑。人本质上是历史的，在时间尺度下微小的变化会成长为巨大的差异。

如果你跟我一样是80年代末90年代初婴儿潮一代，到了今天应该是忙碌而焦虑的状态，说白了现在社会对年轻人的希望是同时负担起养老负担与子女教育，不忙碌焦虑才怪。财富累积与生活方式的改进可能是大多数人无法摆脱的负担，工资也许在涨，但花销也在涨。据我观察，这个年龄段的人大都陷入了信用卡、保险与常旅客积分里程计划的研究之中。背后的逻辑很简单，通货膨胀。

如果今天有个产品年化增长率5%，那么10年复合增长率就是$1.05^{10} - 1 = 0.63$，也就是说，100块放10年就变成了163块。你看到的是变多了，其实这里面忽略了货币购买力问题，如果现在100元可以买一袋大米，10年后一袋大米成了163块，那你其实只实现了保值。如果10年后一袋大米变成200块，那其实这个年化增长率5%的产品的最大意义就是如果你现在有100元没有需求去消费，那么买这个产品可以一定程度让其购买力减退没那么快。

同时你可能也反应过来了，如果现在就有需求，那么应该优先满足现在的需求，因为跑赢通胀是在你有闲钱的情况下该考虑的，如果你没有闲钱，优先考虑消费，不然你以后要付出更多来实现同等程度的需求满足。所有向你兜售理财产品的人基本都不提通胀的影响而是给你展示绝对量变化，这在我看来就是欺诈，忽略基线的欺诈。

这个时间尺度的基线可能是现代社会运作的一个核心，作为个体，你体会的更多是静态，而社会总是在时间轴上一去不返。这里我们做一个基本假设，社会总需求主要由人口决定，如果社会总财富的累积速度低于人口增长，那么每个人的生活条件应该是下行的；如果高于人口增长，那么总体收益。目前我们面对的是后者，一个可预期的后果是，社会结构不变，那么社会累积的财富有两个去向：一个是通过通货膨胀来维持需求价值，另一个则是通过财富集中来维持货币与需求的对应关系。现在来看，两者都在起作用，特别是后者。不过由于前者的存在，整体生活质量是改善的，但后者则可能造成底层人的生活质量下降。同时财富的集中按照《21世纪资本论》的观点应该是向上集中、向富有国家集中。但具体到个人我要加上一个显然但容易忽视的结果：向年长者集中。

在《社会动物》中，作者提到了一个现象：18-34岁美国人平均每年会收到来自父母38000美元的资助。这个现象就是啃老，它已经使各个发达国家潜在的社会生活结构变化了，我所在的系有个技术人员，女儿20多岁但就是不肯出去找工作，还跟女朋友一起生活在家中，这个技术人员自己是典型西方人，很早就脱离原有家庭，但如今却面临自己孩子无法脱离自己家庭的状况。同样，国内到这边读书的留学生也基本是来了就买房置产，然后全家移民，用的自然是家里的资助。不论东西方，年轻人都面临了巨大的压力，如果没有家庭结构的支持，很难独立。但同时要注意到是，家庭结构也在现代社会运作下在不断解体为个体，大城市的单身中青年比例也在升高，这些结果混合到一起让基于现有模式的预测变得困难。我们的父母在置产上更多是自己累积财富；而到了我们这一代，来自家庭的启动资金对于维持生活逐渐变得必不可少；下一代的教育成长成本的增长则一定程度降低了人口出生率。发达国家财富向年长者的集中或者说代际间的财富转移所造成的社会现象是很值得关注的。这是时间与利率的魔力，也是很多问题的根源，例如如果人工智能会取代一些劳动岗位，那么已经在岗的人数可能出于工会压力不会变化太多，但有可能取消掉计划中年轻人的新岗位，这看起来会更平稳，但代际不平等会不断加剧，这个会对社会产生什么影响，很难预期，因为似乎是个阶段性问题。

## 三间分布

其实不只是时间，加上空间与人群间的分布统称三间分布，是环境科学论文解读的一个简化视角。也是现在看待社会问题的一个基本视角，例如当新生事物出现时，系统的研究会同时考虑其地理分布、时间尺度分布与波及人群的画像。具体到污染物研究，空间分布特征、时间分布规律与流行病调查是环境过程研究阅读时必须关注的。具体到材料研究，元素表征与电镜就是空间尺度研究，动力学例如吸附过程、团聚过程就是时间尺度，各领域的应用就算是人群间研究。具体到组学研究，空间分布是让你找出组间差异并注释，时间分布是让你找出组内时间序列差异并注释，人群分布可以理解成找个切入角度把注释讲成故事。具体到经济学就是横向与纵向数据分析，不同学科间似乎潜在一个统一的研究框架，当然，我现在并无法清晰描述，只是感觉。

科研结果的解读是有章可循的，根源上要回溯到物理里关于热力学与动力学的区分，跟人扯上关系就是应用。这类解读本质上还是基于实验或观察数据发现规律，但其实还有一种思路也在某些不容易做实验的学科里流行，那就是基于模型或机制，特别是工科。大量的仿真结果基于规律演绎也可能很好的解决实际问题。那么这个思路如果应用到无法实验的社会现象上是一种过度简化还是新洞见的发现方法。科学研究中控制一个变量，随机其他变量可以很好说明一些问题，但现在面向问题的研究中变量间的相互影响是巨大的，面对复杂系统需要新的解读方式。一种是逻辑清晰但解释力很差的模式，另一种则是表面逻辑混乱但实用性强的模式，我越来越感觉新的数学工具而不是统计学工具应该被引入到这个过程之中，当然，我讲不出什么道理，只是感觉。

作为一个社会动物，了解时间尺度的利率可能生活轻松些，了解科研方法则可能让思考上更有框架感。最后推荐下戴维·布鲁克斯的TED演讲，应该说获取新知不要拘泥于形式，怎么方便怎么来。最后的最后跟现在赶论文的毕业生一个过来人的经验：

语音输入