---
title: 短链氯化石蜡的定量方法
author: ''
date: '2018-08-06'
slug: sccp
categories: []
tags:
  - data
  - tech
---

短链氯化石蜡的定量在环境分析化学中属于难度比较高的，在目的性分析里也算是最非传统的了，不过理解了这类物质的定量对于理解环境分析的复杂性很有帮助，鉴于目前教科书里肯定没有，我就总结在这里。

## 定量分析

分析化学里的定量模型比较简单，你知道待测物的某个指标，在不同含量下测定标准品中这个指标，找出含量与指标的关系模型。然后当测定样品时，将测得的指标带入关系模型就可以得到含量了。用色谱质谱联用来说明就是首先购买待测物的纯品，然后优化色谱质谱条件来获得待测物特定离子响应色谱峰的最佳灵敏度与分离效果，然后配置不同浓度标准溶液进样，根据浓度与峰面积绘制标准曲线。当然说是标准曲线，多数是用线性关系，有了标线就可以测定位置样品中浓度了。

## 短链氯化石蜡

针对短链氯化石蜡，上面那个传统套路是走不通的，原因有三个：

- 短链氯化石蜡并不是一种化合物，而是碳原子数10-13个，氯原子数5-10个的短链烷烃。这是一类化合物，分子式就有24种，而结构式就要上万种了

- 标准品不是纯品，化学定量分析要求标准物纯度要非常高，但市售短链氯化石蜡的标准品大都不是单体，甚至同一种分子式都做不到，能买到的都是用氯含量来标定，也就是定量要通过氯含量来换算

- 分离困难，因为标准不纯，定量要同时测多种短链氯化石蜡，但不同短链氯化石蜡特征离子几乎一样，且中链氯化石蜡会形成干扰，后果就是质谱提取特征离子时有时包含了两种化合物，这样就存在系统性定量偏高，同样的，色谱分离也做不到基线分离，甚至看不到峰，标准品看到的也只是五指峰

由于上述原因，那些基于特征离子定量且又是低分辨质谱定量的方法几乎可以肯定是不靠谱的，线性关系一塌糊涂不说误差不是一般的高。有意思的是，网上可以搜到很多短链氯化石蜡定量方法专利，基本都是胡说八道，根本就没搞清楚问题的复杂性，要么就是隐藏技术细节，但其实很多文献里都有也不用隐藏，且根本就不该出现这类专利，因为学术期刊早就发表过了。我自己申请过也获得过专利，那帮审专利的人专业水平不是一般的低，很大程度是因为外行评价内行，不过这东西挺唬人的，但其实科技领域越前沿胡说八道就越多，这样才有讨论空间，不必看得太重。

## 高分辨质谱定量方法

离子源肯定要是负化学源，EI源会把短链烷烃打碎，后果就是根本找不到特征离子，负化学源能保证你起码找得到分子离子峰。不过这么说也不对，因为即使在负化学源下，短链氯化石蜡的基峰也是掉一个氯原子的。而且只要有氯原子就会存在同位素峰，同位素峰之间在低分辨质谱上会互相覆盖，这里我们先不讨论低分辨定量，高分辨质谱是可以在质谱上实现每种分子式的分离的。

那么色谱用什么呢？首先得是能接质谱的柱子，其次因为短链氯化石蜡沸点不高，我们可以用气相色谱柱来进行分离。当然也有用液相分离的，那个比较复杂就不提了。

好了，我们来看技术难点，我们手上有的标准只标注了氯含量而不是单体含量，所以首先我们要构建氯含量与单体含量的关系。不同氯含量的标准会有不同质谱响应因子，也就是你进样量相同时，峰面积是不同的。这里文献中一般采用的策略就是假设所有短链氯化石蜡单体响应的不同主要来自于氯含量不同，而氯含量不同是因为组成不同。计算出氯均一化后总体氯化度对应的响应因子与样品峰面积就可以知道含量。

首先，我们需要固定浓度不同氯化度的sccp标样，然后提取离子计算面积积分，各离子面积要先除以离子同位素丰度得到化合物面积，然后除氯原子个数得到单位氯原子化合物的响应，所有离子响应之和为单位氯原子的总面积，每个离子的氯化度是已知的，用其单位离子响应占总响应的比例乘以氯化度求和可得到样品中的总氯化度，单位氯原子的总面积除以质量得到标准响应因子，这个响应因子在不同氯化度下不一样，用不同氯化度标样分别测定，得到氯化度与响应因子的回归曲线。

然后，测定样品时只要计算出样品中的总氯化度就可以知道样品响应因子，根据样品中计算出的单位氯原子的响应面积就可以知道其中sccp的总含量。同时也可以反推得到样品中不同单体的浓度组成。不过最好先用标准品作为样品检验下方法是否有系统偏差。

我在`enviGCMS`包里已经做了一个应用，你按照里面说的一步步来是可以实现定量的，不过请一定理解背后的假设，启动应用的代码如下：

~~~
install.packages('enviGCMS')
enviGCMS::runsccp()
~~~

此时你的浏览器会弹出图形界面，按照指示做就可以了，记得去引 references 选项卡里的文献与这个软件包就可以了，我不是方法的发明人，但软件却是我写的。

## 低分辨质谱定量方法

前面提到，在低分辨质谱上存在同一个离子实际是两种物质的情况，如果两组物质质量数干扰，就选两个共有离子，每个离子响应是来自两个物质响应的线形加和，由于两个离子的丰度比可以事先计算出来，所以可以构建下面的方程：

物质A、B的两个共有离子峰面积X、Y，两者丰度比例 m、n：

$$A + B = X$$

$$A\frac{n}{m}+B\frac{n}{m} = Y$$

联立求解可以得到A与B的真实峰面积。

如此可以把相互干扰的离子对放到一起去测，然后求解各离子的实际比例。

这是个穷人的方法，买不起高分辨就要用数据处理来矫正误差，这里我就不写图形界面了，穷要有穷的志气，穷还不愿思考动手，那我也不想帮忙了，线索已经给的很明确了。至于说高分辨为什么写原因也很简单，目前有人要用，而且我知道对方是理解背后原理的，我不希望不理解原理就套用模版套路来进行科研的人（但写作可以用模版方便交流），这样做出的东西意义不大，没有思考的科研也许有用，但丧失了乐趣。

祝大家短链氯化石蜡定量快乐！