<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Meta-Workflow</title>
  <meta name="description" content="This is a workflow for metabolomics studies.">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="Meta-Workflow" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a workflow for metabolomics studies." />
  <meta name="github-repo" content="yufree/metaworkflow" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Meta-Workflow" />
  
  <meta name="twitter:description" content="This is a workflow for metabolomics studies." />
  

<meta name="author" content="Miao YU">


<meta name="date" content="2017-07-04">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="common-analysis-methods-for-metabolomics.html">
<link rel="next" href="case-studyselected.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Metabolomics Workflow</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#reviews-and-tutorials"><i class="fa fa-check"></i><b>1.1</b> Reviews and tutorials</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exprimental-designdoe.html"><a href="exprimental-designdoe.html"><i class="fa fa-check"></i><b>2</b> Exprimental design(DoE)</a></li>
<li class="chapter" data-level="3" data-path="pretreatment.html"><a href="pretreatment.html"><i class="fa fa-check"></i><b>3</b> Pretreatment</a></li>
<li class="chapter" data-level="4" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html"><i class="fa fa-check"></i><b>4</b> Raw data pretreatment</a><ul>
<li class="chapter" data-level="4.1" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#spectral-deconvolution"><i class="fa fa-check"></i><b>4.1</b> Spectral deconvolution</a></li>
<li class="chapter" data-level="4.2" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#correction"><i class="fa fa-check"></i><b>4.2</b> Correction</a></li>
<li class="chapter" data-level="4.3" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#dynamic-range"><i class="fa fa-check"></i><b>4.3</b> Dynamic Range</a><ul>
<li class="chapter" data-level="4.3.1" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#non-detects"><i class="fa fa-check"></i><b>4.3.1</b> Non-detects</a></li>
<li class="chapter" data-level="4.3.2" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#over-detection-limit"><i class="fa fa-check"></i><b>4.3.2</b> Over detection limit</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#adjust-for-unwanted-variances-with-known-batch"><i class="fa fa-check"></i><b>4.4</b> Adjust for unwanted variances with known batch</a><ul>
<li class="chapter" data-level="4.4.1" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#centering"><i class="fa fa-check"></i><b>4.4.1</b> Centering</a></li>
<li class="chapter" data-level="4.4.2" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#scaling"><i class="fa fa-check"></i><b>4.4.2</b> Scaling</a></li>
<li class="chapter" data-level="4.4.3" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#quantile"><i class="fa fa-check"></i><b>4.4.3</b> Quantile</a></li>
<li class="chapter" data-level="4.4.4" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#ratio-based-calibraton"><i class="fa fa-check"></i><b>4.4.4</b> Ratio based calibraton</a></li>
<li class="chapter" data-level="4.4.5" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#linear-normalizer"><i class="fa fa-check"></i><b>4.4.5</b> Linear Normalizer</a></li>
<li class="chapter" data-level="4.4.6" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#regression-calibration"><i class="fa fa-check"></i><b>4.4.6</b> Regression calibration</a></li>
<li class="chapter" data-level="4.4.7" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#batch-normalizer"><i class="fa fa-check"></i><b>4.4.7</b> Batch Normalizer</a></li>
<li class="chapter" data-level="4.4.8" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#internal-standards"><i class="fa fa-check"></i><b>4.4.8</b> Internal standards</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#adjust-for-unwanted-variance-with-unknown-batch"><i class="fa fa-check"></i><b>4.5</b> Adjust for unwanted variance with unknown batch</a><ul>
<li class="chapter" data-level="4.5.1" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#sva"><i class="fa fa-check"></i><b>4.5.1</b> SVA</a></li>
<li class="chapter" data-level="4.5.2" data-path="raw-data-pretreatment.html"><a href="raw-data-pretreatment.html#ruv"><i class="fa fa-check"></i><b>4.5.2</b> RUV</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="peaks-selection.html"><a href="peaks-selection.html"><i class="fa fa-check"></i><b>5</b> Peaks selection</a></li>
<li class="chapter" data-level="6" data-path="annotation.html"><a href="annotation.html"><i class="fa fa-check"></i><b>6</b> Annotation</a><ul>
<li class="chapter" data-level="6.1" data-path="annotation.html"><a href="annotation.html#tools"><i class="fa fa-check"></i><b>6.1</b> Tools</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="omics-analysis.html"><a href="omics-analysis.html"><i class="fa fa-check"></i><b>7</b> Omics analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="omics-analysis.html"><a href="omics-analysis.html#pathway-analysis"><i class="fa fa-check"></i><b>7.1</b> Pathway analysis</a></li>
<li class="chapter" data-level="7.2" data-path="omics-analysis.html"><a href="omics-analysis.html#network-analysis"><i class="fa fa-check"></i><b>7.2</b> Network analysis</a></li>
<li class="chapter" data-level="7.3" data-path="omics-analysis.html"><a href="omics-analysis.html#omics-integration"><i class="fa fa-check"></i><b>7.3</b> Omics integration</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="common-analysis-methods-for-metabolomics.html"><a href="common-analysis-methods-for-metabolomics.html"><i class="fa fa-check"></i><b>8</b> Common analysis methods for metabolomics</a><ul>
<li class="chapter" data-level="8.1" data-path="common-analysis-methods-for-metabolomics.html"><a href="common-analysis-methods-for-metabolomics.html#pca"><i class="fa fa-check"></i><b>8.1</b> PCA</a></li>
<li class="chapter" data-level="8.2" data-path="common-analysis-methods-for-metabolomics.html"><a href="common-analysis-methods-for-metabolomics.html#cluster-analysis"><i class="fa fa-check"></i><b>8.2</b> Cluster Analysis</a></li>
<li class="chapter" data-level="8.3" data-path="common-analysis-methods-for-metabolomics.html"><a href="common-analysis-methods-for-metabolomics.html#plsda"><i class="fa fa-check"></i><b>8.3</b> PLSDA</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="demo.html"><a href="demo.html"><i class="fa fa-check"></i><b>9</b> Demo</a><ul>
<li class="chapter" data-level="9.1" data-path="demo.html"><a href="demo.html#project-setup"><i class="fa fa-check"></i><b>9.1</b> Project Setup</a></li>
<li class="chapter" data-level="9.2" data-path="demo.html"><a href="demo.html#data-input"><i class="fa fa-check"></i><b>9.2</b> Data input</a></li>
<li class="chapter" data-level="9.3" data-path="demo.html"><a href="demo.html#find-the-peaks"><i class="fa fa-check"></i><b>9.3</b> Find the peaks</a></li>
<li class="chapter" data-level="9.4" data-path="demo.html"><a href="demo.html#data-correction"><i class="fa fa-check"></i><b>9.4</b> Data correction</a></li>
<li class="chapter" data-level="9.5" data-path="demo.html"><a href="demo.html#statistic-analysis"><i class="fa fa-check"></i><b>9.5</b> Statistic analysis</a></li>
<li class="chapter" data-level="9.6" data-path="demo.html"><a href="demo.html#annotation-1"><i class="fa fa-check"></i><b>9.6</b> Annotation</a></li>
<li class="chapter" data-level="9.7" data-path="demo.html"><a href="demo.html#omics-analysis-1"><i class="fa fa-check"></i><b>9.7</b> Omics analysis</a></li>
<li class="chapter" data-level="9.8" data-path="demo.html"><a href="demo.html#metaboanalyst"><i class="fa fa-check"></i><b>9.8</b> MetaboAnalyst</a></li>
<li class="chapter" data-level="9.9" data-path="demo.html"><a href="demo.html#visulizing-peaks"><i class="fa fa-check"></i><b>9.9</b> Visulizing Peaks</a></li>
<li class="chapter" data-level="9.10" data-path="demo.html"><a href="demo.html#optimation-of-xcms"><i class="fa fa-check"></i><b>9.10</b> Optimation of XCMS</a></li>
<li class="chapter" data-level="9.11" data-path="demo.html"><a href="demo.html#summary"><i class="fa fa-check"></i><b>9.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="case-studyselected.html"><a href="case-studyselected.html"><i class="fa fa-check"></i><b>10</b> Case Study(selected)</a><ul>
<li class="chapter" data-level="10.1" data-path="case-studyselected.html"><a href="case-studyselected.html#cancer"><i class="fa fa-check"></i><b>10.1</b> Cancer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="11" data-path="batch-effect.html"><a href="batch-effect.html"><i class="fa fa-check"></i><b>11</b> Batch effect</a><ul>
<li class="chapter" data-level="11.0.1" data-path="batch-effect.html"><a href="batch-effect.html#detection-of-unmodeled-factors"><i class="fa fa-check"></i><b>11.0.1</b> Detection of unmodeled factors</a></li>
<li class="chapter" data-level="11.0.2" data-path="batch-effect.html"><a href="batch-effect.html#construction-of-surrogate-variables"><i class="fa fa-check"></i><b>11.0.2</b> Construction of surrogate variables</a></li>
<li class="chapter" data-level="11.0.3" data-path="batch-effect.html"><a href="batch-effect.html#case-study"><i class="fa fa-check"></i><b>11.0.3</b> Case study</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/yufree/metaworkflow" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Meta-Workflow</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="demo" class="section level1">
<h1><span class="header-section-number">Chapter 9</span> Demo</h1>
<div id="project-setup" class="section level2">
<h2><span class="header-section-number">9.1</span> Project Setup</h2>
<p>I suggest building your data analysis projects in RStudio(Click File - New project - New dictionary - Empty project). Then assign a name for your project. I also recommend the following tips if you are familiar with it.</p>
<ul>
<li><p>Use <a href="https://git-scm.com/">git</a>/<a href="https://github.com/">github</a> to make version control of your code and sync your project online.</p></li>
<li><p>NOT use your name for your project because other peoples might cooperate with you and someone might check your data when you publish your papers. Each project should be a work for one paper or one chapter in your thesis.</p></li>
<li><p>Use <strong>workflow</strong> document(txt or doc) in your project to record all of the steps and code you performed for this project. Treat this document as digital version of your experiment notebook</p></li>
<li><p>Use <strong>data</strong> folder in your project folder for the raw data and the results you get in data analysis</p></li>
<li><p>Use <strong>figure</strong> folder in your project folder for the figure</p></li>
<li><p>Use <strong>munuscript</strong> folder in your project folder for the manuscript (you could write paper in rstudio with the help of template in <a href="https://github.com/rstudio/rticles">Rmarkdown</a>)</p></li>
<li><p>Just double click <strong>[yourprojectname].Rproj</strong> to start your project</p></li>
</ul>
</div>
<div id="data-input" class="section level2">
<h2><span class="header-section-number">9.2</span> Data input</h2>
<p><strong>xcms</strong> does not support all of the Raw files from every mass spectrometry manufacturers. You need to convert your Raw data into some open-source <a href="https://en.wikipedia.org/wiki/Mass_spectrometry_data_format">data format</a> such as mzData, mzXML or CDF files. The tool is <strong>MScovert</strong> from <a href="http://proteowizard.sourceforge.net/"><strong>ProteoWizard</strong></a>.</p>
<p>Here is a demo:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># install the packages for data analysis and </span>
<span class="co"># source(&quot;https://bioconductor.org/biocLite.R&quot;)</span>
<span class="co"># biocLite(c(&quot;multtest&quot;,&quot;faahKO&quot;,&quot;xcms&quot;,&quot;qvalue&quot;,&quot;CAMERA&quot;))</span>
<span class="co"># load the functions and dataset for demo</span>

<span class="kw">library</span>(multtest)
<span class="kw">library</span>(xcms)
<span class="kw">library</span>(faahKO)
<span class="kw">library</span>(BiocParallel)
<span class="co"># get the demo data in faahKO packages</span>
cdfpath &lt;-<span class="st"> </span><span class="kw">system.file</span>(<span class="st">&quot;cdf&quot;</span>,<span class="dt">package =</span> <span class="st">&quot;faahKO&quot;</span>)
<span class="co"># show the name of demo data</span>
<span class="kw">list.files</span>(cdfpath,<span class="dt">recursive =</span> T)</code></pre></div>
<pre><code>##  [1] &quot;KO/ko15.CDF&quot; &quot;KO/ko16.CDF&quot; &quot;KO/ko18.CDF&quot; &quot;KO/ko19.CDF&quot; &quot;KO/ko21.CDF&quot;
##  [6] &quot;KO/ko22.CDF&quot; &quot;WT/wt15.CDF&quot; &quot;WT/wt16.CDF&quot; &quot;WT/wt18.CDF&quot; &quot;WT/wt19.CDF&quot;
## [11] &quot;WT/wt21.CDF&quot; &quot;WT/wt22.CDF&quot;</code></pre>
<p>Here is a demo for <em>xcmsSet</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cdffiles &lt;-<span class="st"> </span><span class="kw">list.files</span>(cdfpath, <span class="dt">recursive =</span> <span class="ot">TRUE</span>, <span class="dt">full.names =</span> <span class="ot">TRUE</span>)
xset &lt;-<span class="st"> </span><span class="kw">xcmsSet</span>(cdffiles)
xset</code></pre></div>
<pre><code>## An &quot;xcmsSet&quot; object with 12 samples
## 
## Time range: 2506.1-4147.7 seconds (41.8-69.1 minutes)
## Mass range: 200.1-599.3338 m/z
## Peaks: 4721 (about 393 per sample)
## Peak Groups: 0 
## Sample classes: KO, WT 
## 
## Feature detection:
##  o Peak picking performed on MS1.
## Profile settings: method = bin
##                   step = 0.1
## 
## Memory usage: 0.74 MB</code></pre>
</div>
<div id="find-the-peaks" class="section level2">
<h2><span class="header-section-number">9.3</span> Find the peaks</h2>
<p>The first step to process the MS data is that find the peaks against the noises. In <strong>xcms</strong>, all of related staffs are handled by <em>xcmsSet</em> function.</p>
<p>For any functions in <strong>xcms</strong> or <strong>R</strong>, you could get their documents by type <code>?</code> before certain function. Another geek way is input the name of the function in the console of Rstudio and press F1 for help.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?xcmsSet</code></pre></div>
<p>In the document of <em>xcmsset</em>, we could set the sample classes, profmethod, profparam, polarity,etc. In the online version, such configurations are shown in certain windows. In the local analysis environment, such parameters are setup by yourselves. However, I think the default configurations could satisfied most of the analysis because related information should have been recorded in your Raw data and <strong>xcms</strong> could find them. All you need to do is that show the data dictionary for <em>xcmsSet</em>.</p>
<p>If your data have many groups such as control and treated group, just put them in separate subfolder of the data folder and <em>xcmsSet</em> would read them as separated groups.</p>
<p>The output was an object with class of <em>xcmsSet</em>. You could see a summary by type the name. In this cases, <em>xcmsSet</em> found 4721 peaks with time range 41.8-69.1 min and mass range 200.1-599.3338 m/z in the 12 samples.</p>
<p>Another function which might be useful is <code>group</code>. This function will add additional information about the same analytes for <code>xcmsSet</code> objects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset &lt;-<span class="st"> </span><span class="kw">group</span>(xset)</code></pre></div>
<pre><code>## Processing 3195 mz slices ...</code></pre>
<pre><code>## OK</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset</code></pre></div>
<pre><code>## An &quot;xcmsSet&quot; object with 12 samples
## 
## Time range: 2506.1-4147.7 seconds (41.8-69.1 minutes)
## Mass range: 200.1-599.3338 m/z
## Peaks: 4721 (about 393 per sample)
## Peak Groups: 403 
## Sample classes: KO, WT 
## 
## Feature detection:
##  o Peak picking performed on MS1.
## Profile settings: method = bin
##                   step = 0.1
## 
## Memory usage: 0.804 MB</code></pre>
<p>Now you see there are 403 groups in the demo data, which meant 403 analytes are found across 4721 peaks.</p>
</div>
<div id="data-correction" class="section level2">
<h2><span class="header-section-number">9.4</span> Data correction</h2>
<p>Reasons of data correction might come from many aspects such as the unstable instrument and pollution on column. In <strong>xcms</strong>, the most important correction is retention time correction.</p>
<p>Remember the original retention time might changed and use another object to save the new object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset2 &lt;-<span class="st"> </span><span class="kw">retcor</span>(xset, <span class="dt">method =</span> <span class="st">&quot;obiwarp&quot;</span>)</code></pre></div>
<pre><code>## center sample:  ko16 
## Processing: ko15</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ...</code></pre>
<pre><code>## OK</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ...</code></pre>
<pre><code>## OK</code></pre>
<pre><code>## ko18</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## ko19</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## ko21</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## ko22</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt15</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt16</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt18</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt19</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt21</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<pre><code>## wt22</code></pre>
<pre><code>## Create profile matrix with method &#39;bin&#39; and step 1 ... OK</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset2</code></pre></div>
<pre><code>## An &quot;xcmsSet&quot; object with 12 samples
## 
## Time range: 2506.3-4162.2 seconds (41.8-69.4 minutes)
## Mass range: 200.1-599.3338 m/z
## Peaks: 4721 (about 393 per sample)
## Peak Groups: 0 
## Sample classes: KO, WT 
## 
## Feature detection:
##  o Peak picking performed on MS1.
## Profile settings: method = bin
##                   step = 0.1
## 
## Memory usage: 0.74 MB</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># you need group the peaks again for this corrected data</span>
xset2 &lt;-<span class="st"> </span><span class="kw">group</span>(xset2)</code></pre></div>
<pre><code>## Processing 3195 mz slices ... OK</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset2</code></pre></div>
<pre><code>## An &quot;xcmsSet&quot; object with 12 samples
## 
## Time range: 2506.3-4162.2 seconds (41.8-69.4 minutes)
## Mass range: 200.1-599.3338 m/z
## Peaks: 4721 (about 393 per sample)
## Peak Groups: 404 
## Sample classes: KO, WT 
## 
## Feature detection:
##  o Peak picking performed on MS1.
## Profile settings: method = bin
##                   step = 0.1
## 
## Memory usage: 0.804 MB</code></pre>
<p>You see one more peak groups after the correction. After the retention time correction, we also need to correct the peak groups by filling the missing peaks. Such function calls <em>fillpeaks</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset3 &lt;-<span class="st"> </span><span class="kw">fillPeaks</span>(xset2,<span class="dt">BPPARAM=</span><span class="kw">SnowParam</span>())</code></pre></div>
<pre><code>## /home/travis/R/Library/faahKO/cdf/KO/ko15.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/KO/ko16.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/KO/ko18.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/KO/ko19.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/KO/ko21.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/KO/ko22.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt15.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt16.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt18.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt19.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt21.CDF 
## method:  bin 
## step:  0.1 
## /home/travis/R/Library/faahKO/cdf/WT/wt22.CDF 
## method:  bin 
## step:  0.1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">xset3</code></pre></div>
<pre><code>## An &quot;xcmsSet&quot; object with 12 samples
## 
## Time range: 2502.9-4162.2 seconds (41.7-69.4 minutes)
## Mass range: 200.1-599.3338 m/z
## Peaks: 6054 (about 504 per sample)
## Peak Groups: 404 
## Sample classes: KO, WT 
## 
## Feature detection:
##  o Peak picking performed on MS1.
## Profile settings: method = bin
##                   step = 0.1
## 
## Memory usage: 0.945 MB</code></pre>
<p>You see more peaks found.</p>
</div>
<div id="statistic-analysis" class="section level2">
<h2><span class="header-section-number">9.5</span> Statistic analysis</h2>
<p>Right now we get peaks across samples, the next step is finding the differences between two groups. You will find the P values of t-test for pairwise comparison:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">reporttab &lt;-<span class="st"> </span><span class="kw">diffreport</span>(xset3, <span class="st">&quot;WT&quot;</span>, <span class="st">&quot;KO&quot;</span>, <span class="st">&quot;example&quot;</span>)
reporttab[<span class="dv">1</span>:<span class="dv">3</span>,]</code></pre></div>
<pre><code>##        name     fold    tstat       pvalue    mzmed    mzmin    mzmax
## 1 M300T3391 5.693594 14.44368 5.026336e-08 300.1898 300.1706 300.2000
## 2 M301T3391 6.283030 15.52501 5.385022e-08 301.1879 301.1659 301.1949
## 3 M298T3185 3.984984 11.88773 3.615841e-07 298.1508 298.1054 298.1592
##      rtmed    rtmin    rtmax npeaks KO WT      ko15      ko16      ko18
## 1 3390.699 3374.142 3398.743     12  6  6 4534353.6 4980914.5 5290739.1
## 2 3391.126 3385.366 3394.937      7  6  1  962353.4 1047934.1 1109303.0
## 3 3185.221 3182.083 3190.163      4  4  0  180780.8  204134.9  191015.9
##        ko19      ko21      ko22      wt15      wt16      wt18      wt19
## 1 4564262.9 4733236.1 3931592.6 349660.89 491793.18 645526.70 634108.85
## 2  946943.4  984787.2  806171.5  80639.28 118940.90 134531.39 102784.65
## 3  190626.8  155276.9  220288.6  16448.42  41050.04  50082.55  76704.81
##         wt21       wt22
## 1 1438254.45 1364627.84
## 2  203982.76  291392.97
## 3   53957.78   48363.33</code></pre>
<p>Now you have got the ions that varies a lot between groups. Such ions are things we should take care of. In a ideal case, this is the endpoint of your study and the left work is making a report of your finding.</p>
<p>However,we need q-values to control FDR. To get the q-values, you need input p-values and use the function from <strong>qvalue</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(qvalue)
<span class="co"># extract the p-value to caculate q-value</span>
qvalue &lt;-<span class="st"> </span><span class="kw">qvalue</span>(<span class="dt">p=</span>reporttab$pvalue)
<span class="co"># add qvalue to reporttab</span>
reporttab$qvalue &lt;-<span class="st"> </span>qvalue$qvalues
<span class="co"># reporttab[1:3,]</span></code></pre></div>
<p>For further information about q-value, check <a href="https://en.wikipedia.org/wiki/False_discovery_rate#q-value">here</a>.</p>
<p>After the FDR control, the following steps depend on your study.</p>
</div>
<div id="annotation-1" class="section level2">
<h2><span class="header-section-number">9.6</span> Annotation</h2>
<p>I suggest <strong>CAMERA</strong> package to handle this task. You need to prepare an object of class <em>xcmsSet</em>, for example, <em>xset3</em>(remember to use <em>fillpeaks</em> to get the ions group).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(CAMERA)
<span class="co"># Create an xsAnnotate object</span>
xsa &lt;-<span class="st"> </span><span class="kw">xsAnnotate</span>(xset3)
<span class="co"># Group after RT value of the xcms grouped peak</span>
xsaF &lt;-<span class="st"> </span><span class="kw">groupFWHM</span>(xsa, <span class="dt">perfwhm=</span><span class="fl">0.6</span>)</code></pre></div>
<pre><code>## Start grouping after retention time.
## Created 132 pseudospectra.</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Verify grouping</span>
xsaC &lt;-<span class="st"> </span><span class="kw">groupCorr</span>(xsaF)</code></pre></div>
<pre><code>## Start grouping after correlation.
## Generating EIC&#39;s .. 
## 
## Calculating peak correlations in 132 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## 
## Calculating graph cross linking in 132 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## New number of ps-groups:  202 
## xsAnnotate has now 202 groups, instead of 132</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Annotate isotopes, could be done before groupCorr</span>
xsaFI &lt;-<span class="st"> </span><span class="kw">findIsotopes</span>(xsaC)</code></pre></div>
<pre><code>## Generating peak matrix!
## Run isotope peak annotation
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## Found isotopes: 57</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Annotate adducts</span>
xsaFA &lt;-<span class="st"> </span><span class="kw">findAdducts</span>(xsaFI, <span class="dt">polarity=</span><span class="st">&quot;positive&quot;</span>)</code></pre></div>
<pre><code>## Generating peak matrix for peak annotation!
## 
## Calculating possible adducts in 202 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># See the results</span>
<span class="kw">getPeaklist</span>(xsaFA)[<span class="dv">1</span>:<span class="dv">3</span>,]</code></pre></div>
<pre><code>##         mz    mzmin    mzmax       rt    rtmin    rtmax npeaks KO WT
## 1 200.1000 200.1000 200.1000 2924.027 2876.967 2939.450      9  4  5
## 2 205.0000 205.0000 205.0000 2788.377 2782.719 2795.550     12  6  6
## 3 205.9927 205.9786 206.0023 2789.144 2782.719 2793.925     12  6  6
##        ko15      ko16       ko18       ko19       ko21      ko22      wt15
## 1  147887.5  451600.7   65290.38   52834.57   70042.53  162012.4  175177.1
## 2 1778568.9 1567038.1 1482796.38 1039129.82 1223132.35 1072037.7 1950287.5
## 3  237993.6  269714.0  201393.42  150107.31  176989.65  156797.0  276541.8
##         wt16       wt18       wt19      wt21       wt22  isotopes
## 1   82619.48   46255.03   69198.22  153273.5   98144.28          
## 2 1466780.60 1572679.16 1275312.76 1356014.3 1231442.16   [1][M]+
## 3  222366.15  211717.71  186850.88  188285.9  172348.76 [1][M+1]+
##            adduct pcgroup
## 1                     165
## 2 [M+Na]+ 182.007       5
## 3                       5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Get final peaktable and store on harddrive</span>
<span class="co"># write.csv(getPeaklist(xsaFA),file=&quot;data/result_CAMERA.csv&quot;)</span></code></pre></div>
<p>Any steps after the <em>annotation</em> could be operated solo and you may not need the isotopes or adducts. You could also use <em>annotateDiffreport</em> to show the results as <em>diffreport</em> in <strong>xcms</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make a diffreport with CAMERA result and extract the fold change higher than 3</span>
dreport &lt;-<span class="st"> </span><span class="kw">annotateDiffreport</span>(xset3, <span class="dt">fc_th =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## Start grouping after retention time.
## Created 132 pseudospectra.
## Generating peak matrix!
## Run isotope peak annotation
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## Found isotopes: 68 
## Start grouping after correlation.
## Generating EIC&#39;s .. 
## 
## Calculating peak correlations in 34 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## 
## Calculating graph cross linking in 34 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## New number of ps-groups:  156 
## xsAnnotate has now 156 groups, instead of 132 
## Generating peak matrix for peak annotation!
## 
## Calculating possible adducts in 58 Groups... 
##  % finished: 10  20  30</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># extract the p-value to caculate q-value</span>
qvalue &lt;-<span class="st"> </span><span class="kw">qvalue</span>(<span class="dt">p=</span>dreport$pvalue)
<span class="co"># add qvalue to reporttab</span>
dreport$qvalue &lt;-<span class="st"> </span>qvalue$qvalues
<span class="co"># See the results</span>
<span class="co"># dreport[1:3,]</span>
<span class="co"># save on harddrive</span>
<span class="co"># write.csv(dreport,file=&#39;data/diffreport.csv&#39;)</span></code></pre></div>
</div>
<div id="omics-analysis-1" class="section level2">
<h2><span class="header-section-number">9.7</span> Omics analysis</h2>
<p>Since we have got the annotations, Omics analysis could be performed. In <strong>xcms</strong>, the default database is <strong>metlin</strong>. You could directly get the link to certain compounds when you generate the differences report.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make a diffreport with CAMERA result and extract the fold change higher than 3, add the metlin links</span>
dreport &lt;-<span class="st"> </span><span class="kw">annotateDiffreport</span>(xset3, <span class="dt">fc_th =</span> <span class="dv">3</span>, <span class="dt">metlin =</span> T)</code></pre></div>
<pre><code>## Start grouping after retention time.
## Created 132 pseudospectra.
## Generating peak matrix!
## Run isotope peak annotation
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## Found isotopes: 68 
## Start grouping after correlation.
## Generating EIC&#39;s .. 
## 
## Calculating peak correlations in 34 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## 
## Calculating graph cross linking in 34 Groups... 
##  % finished: 10  20  30  40  50  60  70  80  90  100  
## New number of ps-groups:  156 
## xsAnnotate has now 156 groups, instead of 132 
## Generating peak matrix for peak annotation!
## 
## Calculating possible adducts in 58 Groups... 
##  % finished: 10  20  30</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># extract the p-value to caculate q-value</span>
qvalue &lt;-<span class="st"> </span><span class="kw">qvalue</span>(<span class="dt">p=</span>dreport$pvalue)
<span class="co"># add qvalue to reporttab</span>
dreport$qvalue &lt;-<span class="st"> </span>qvalue$qvalues
<span class="co"># See the results</span>
dreport[<span class="dv">1</span>:<span class="dv">3</span>,]</code></pre></div>
<pre><code>##                 name     fold     tstat       pvalue    mzmed    mzmin
## 300.2/3391 M300T3391 5.693594 -14.44368 5.026336e-08 300.1898 300.1706
## 301.2/3391 M301T3391 6.283030 -15.52501 5.385022e-08 301.1879 301.1659
## 298.2/3185 M298T3185 3.984984 -11.88773 3.615841e-07 298.1508 298.1054
##               mzmax    rtmed    rtmin    rtmax npeaks KO WT
## 300.2/3391 300.2000 3390.699 3374.142 3398.743     12  6  6
## 301.2/3391 301.1949 3391.126 3385.366 3394.937      7  6  1
## 298.2/3185 298.1592 3185.221 3182.083 3190.163      4  4  0
##                                                                             metlin
## 300.2/3391 http://metlin.scripps.edu/metabo_list.php?mass_min=298.2&amp;mass_max=300.2
## 301.2/3391 http://metlin.scripps.edu/metabo_list.php?mass_min=299.2&amp;mass_max=301.2
## 298.2/3185 http://metlin.scripps.edu/metabo_list.php?mass_min=296.2&amp;mass_max=298.2
##                        ko15             ko16             ko18
## 300.2/3391 4534353.62273683 4980914.48421051 5290739.13866664
## 301.2/3391 962353.429578945 1047934.14136842 1109303.04472222
## 298.2/3185 180780.817277777 204134.864631578 191015.910842105
##                        ko19             ko21             ko22
## 300.2/3391 4564262.89684209 4733236.07999997      3931592.586
## 301.2/3391 946943.392842103 984787.204999993 806171.472899999
## 298.2/3185  190626.84952381 155276.902163857      220288.6218
##                        wt15             wt16             wt18
## 300.2/3391  349660.88536842 491793.181333331 645526.704947367
## 301.2/3391 80639.2842881944 118940.899088542  134531.38671875
## 298.2/3185 16448.4191894531 41050.0418122944 50082.5494449013
##                        wt19             wt21             wt22  isotopes
## 300.2/3391 634108.848947367 1438254.44559999      1364627.844   [4][M]+
## 301.2/3391 102784.647854275 203982.760512408 291392.971409092 [4][M+1]+
## 298.2/3185 76704.8068359375 53957.7833573191  48363.333932977          
##            adduct pcgroup       qvalue
## 300.2/3391             17 1.087774e-05
## 301.2/3391             17 1.087774e-05
## 298.2/3185            103 4.869333e-05</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># save on harddrive</span>
<span class="co"># write.csv(dreport,file=&#39;data/diffreport.csv&#39;)</span></code></pre></div>
</div>
<div id="metaboanalyst" class="section level2">
<h2><span class="header-section-number">9.8</span> MetaboAnalyst</h2>
<p>Actully, after you perform data correction, you have got the data matrix for statistic analysis. You might choose <a href="http://www.metaboanalyst.ca/MetaboAnalyst/faces/docs/Contact.xhtml"><strong>MetaboAnalyst</strong></a> online or offline to make furthor analysis, which supplied more statistical choices than xcms.</p>
<p>The input data format for <strong>MetaboAnalyst</strong> should be rows for peaks and colomns for samples. You could also add groups infomation if possible. Use the following code to get the data for analysis.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">MAdata &lt;-<span class="st"> </span><span class="kw">groupval</span>(xset3,<span class="dt">method =</span> <span class="st">&quot;medret&quot;</span>, <span class="dt">intensity =</span> <span class="st">&quot;into&quot;</span>)
MAdata &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="dt">group =</span> <span class="kw">as.character</span>(<span class="kw">phenoData</span>(xset)$class),MAdata)
<span class="co"># output the data for MetaboAnalyst</span>
<span class="co"># write.csv(MAdata, file = &quot;data/MAdata.csv&quot;)</span></code></pre></div>
</div>
<div id="visulizing-peaks" class="section level2">
<h2><span class="header-section-number">9.9</span> Visulizing Peaks</h2>
<p>If you find some significant peaks, the best way to check them is data visulization. <strong>xcms</strong> supplies such functions. All you need are the retention time and ions’ range.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">eic &lt;-<span class="st"> </span><span class="kw">groups</span>(xset3)
index &lt;-<span class="st"> </span><span class="kw">which</span>(eic[,<span class="st">&quot;rtmed&quot;</span>] &gt;<span class="st"> </span><span class="dv">2500</span> &amp;<span class="st"> </span>eic[,<span class="st">&quot;rtmed&quot;</span>&lt;<span class="dv">2600</span>])[<span class="dv">1</span>]</code></pre></div>
</div>
<div id="optimation-of-xcms" class="section level2">
<h2><span class="header-section-number">9.10</span> Optimation of XCMS</h2>
<p>IPO package could be used to optimaze the parameters for XCMS. Try the following code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mzdatapath &lt;-<span class="st"> </span><span class="kw">system.file</span>(<span class="st">&quot;cdf&quot;</span>,<span class="dt">package =</span> <span class="st">&quot;faahKO&quot;</span>)
mzdatafiles &lt;-<span class="st"> </span><span class="kw">list.files</span>(mzdatapath, <span class="dt">recursive =</span> <span class="ot">TRUE</span>, <span class="dt">full.names=</span><span class="ot">TRUE</span>)
<span class="kw">library</span>(IPO)
peakpickingParameters &lt;-<span class="st"> </span><span class="kw">getDefaultXcmsSetStartingParams</span>(<span class="st">&#39;matchedFilter&#39;</span>)
<span class="co">#setting levels for min_peakwidth to 10 and 20 (hence 15 is the center point)</span>
peakpickingParameters$min_peakwidth &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">20</span>) 
peakpickingParameters$max_peakwidth &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">26</span>,<span class="dv">42</span>)
<span class="co">#setting only one value for ppm therefore this parameter is not optimized</span>
peakpickingParameters$ppm &lt;-<span class="st"> </span><span class="dv">20</span> 
resultPeakpicking &lt;-<span class="st"> </span>
<span class="st">  </span><span class="kw">optimizeXcmsSet</span>(<span class="dt">files =</span> mzdatafiles[<span class="dv">6</span>:<span class="dv">9</span>], 
                  <span class="dt">params =</span> peakpickingParameters, 
                  <span class="dt">nSlaves =</span> <span class="dv">4</span>, 
                  <span class="dt">subdir =</span> <span class="st">&#39;rsmDirectory&#39;</span>)

optimizedXcmsSetObject &lt;-<span class="st"> </span>resultPeakpicking$best_settings$xset

retcorGroupParameters &lt;-<span class="st"> </span><span class="kw">getDefaultRetGroupStartingParams</span>()
retcorGroupParameters$profStep &lt;-<span class="st"> </span><span class="dv">1</span>
resultRetcorGroup &lt;-
<span class="st">  </span><span class="kw">optimizeRetGroup</span>(<span class="dt">xset =</span> optimizedXcmsSetObject, 
                   <span class="dt">params =</span> retcorGroupParameters, 
                   <span class="dt">nSlaves =</span> <span class="dv">4</span>, 
                   <span class="dt">subdir =</span> <span class="st">&quot;rsmDirectory&quot;</span>)


<span class="kw">writeRScript</span>(resultPeakpicking$best_settings$parameters, 
             resultRetcorGroup$best_settings, 
             <span class="dt">nSlaves=</span><span class="dv">12</span>)
<span class="co"># https://github.com/rietho/IPO/blob/master/vignettes/IPO.Rmd</span></code></pre></div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">9.11</span> Summary</h2>
<p>This is the offline metaboliomics data process workflow. For each study, details would be different and F1 is always your best friend.</p>
<p>Enjoy yourself in data mining!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="common-analysis-methods-for-metabolomics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="case-studyselected.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yufree/metaworkflow/edit/master/10-demo.Rmd",
"text": "Edit"
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
