<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.79.1" />


<title>Play with HMDB datasets: Part II - Miao Yu | 于淼 </title>
<meta property="og:title" content="Play with HMDB datasets: Part II - Miao Yu | 于淼 ">



  








<link href='//cdn.bootcss.com/highlight.js/9.9.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">

<script async src="https://use.fontawesome.com/32c3d13def.js"></script>


		    
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-6S0CPNLV6R');
</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-6S0CPNLV6R"></script>
<script src="https://ipmeta.io/plugin.js"></script>
<script>
   provideGtagPlugin({
      serviceProvider: 'dimension1',
      networkDomain: 'dimension2',
      networkType: 'dimension3',
   });
</script>
  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="https://yufree.cn/" class="nav-logo">
    <img src="https://yufree.cn/images/fish.png"
         width="50"
         height="50"
         alt="Yufree">
  </a>

  <ul class="nav-links">
    
    
    
    <li class=""><a href="/"> Home </a></li>
    
    <li class=""><a href="/en/about/"> About </a></li>
    
    <li class=""><a href="/en/"> Blog </a></li>
    
    <li class=""><a href="/en/vitae/"> Vitae </a></li>
    
    <li class=""><a href="https://bookdown.org/yufree/Metabolomics/"> MetaWorkflow </a></li>
    
    <li class=""><a href="/cn/"> 中文 </a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">3 min read</span>
    
    <h1 class="article-title">Play with HMDB datasets: Part II

</h1>


<div class="article-date">
  <span> Miao Yu ·   2018/04/22</span>
  <span class="article-toolbar">
    
    <a href="/en/index.xml" type="application/rss+xml" target="_blank"><i class="fa fa-rss" aria-hidden="true" title="RSS feed"></i></a>
    
    <a href="https://twitter.com/home?status=Play&#43;with&#43;HMDB&#43;datasets%3A&#43;Part&#43;II&#43;https%3A%2F%2Fyufree.cn%2Fen%2F2018%2F04%2F22%2Fplay-with-hmdb-datasets-part-ii%2F&#43;via&#43;%40yu_free" target="_blank"><i class="fa fa-twitter" aria-hidden="true" title="Share via Twitter"></i></a>
    <a href="http://service.weibo.com/share/share.php?content=utf-8&amp;title=Play&#43;with&#43;HMDB&#43;datasets%3A&#43;Part&#43;II&#43;%40%E8%B4%AB%E9%81%93yufree&amp;url=https%3A%2F%2Fyufree.cn%2Fen%2F2018%2F04%2F22%2Fplay-with-hmdb-datasets-part-ii%2F" target="_blank"><i class="fa fa-weibo" aria-hidden="true" title="分享到新浪微博"></i></a>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><i class="fa fa-cc" aria-hidden="true" title="Attribution-NonCommercial-ShareAlike 4.0 International"></i></a>
    
    
    
    <a href="https://github.com/yufree/yufree.cn/edit/master/content/en/2018-04-22-play-with-hmdb-datasets-part-ii.md"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Suggest an edit of this page"></i></a>
    
    </span>
</div>



    
    <div class="article-content">
      <p>Our HMDB data have 114066 metabolites with 13 properties such as hmdb ID, monisotopic_molecular_weight, iupac_name, name, chemical_formula, cas_registry_number, smiles, kingdom, direct_parent, super_class, class, sub_class, molecular_framework. Let&rsquo;s make some explore analysis:</p>
<h2 id="ratio-between-monisotopic-molecular-weight-and-smiles">Ratio between monisotopic molecular weight and smiles</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(tidyverse)
hmdb <span style="color:#f92672">%&gt;%</span>
        <span style="color:#a6e22e">summarise_all</span>(<span style="color:#a6e22e">funs</span>(<span style="color:#a6e22e">n_distinct</span>(.)))
</code></pre></div><pre><code>## # A tibble: 1 x 13
##   accession monisotopic_molecular_weig… iupac_name   name chemical_formula
##       &lt;int&gt;                       &lt;int&gt;      &lt;int&gt;  &lt;int&gt;            &lt;int&gt;
## 1    114066                       13429     113720 114066            11762
## # ... with 8 more variables: cas_registry_number &lt;int&gt;, smiles &lt;int&gt;,
## #   kingdom &lt;int&gt;, direct_parent &lt;int&gt;, super_class &lt;int&gt;, class &lt;int&gt;,
## #   sub_class &lt;int&gt;, molecular_framework &lt;int&gt;
</code></pre><p>We have 13429 monisotopic molecular weight, 11762 chemical formula, 113900 smiles among the 114066 metabolites, which means for each monisotopic molecular weight, you could find ~8.5 metabolites. Different smiles means different structures and this is the main reason why we need MS/MS data. However, we could check the ratio in details.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(tidyverse)
hmdb <span style="color:#f92672">%&gt;%</span>
        <span style="color:#a6e22e">group_by</span>(super_class) <span style="color:#f92672">%&gt;%</span>
        <span style="color:#a6e22e">summarize</span>(ratio <span style="color:#f92672">=</span> <span style="color:#a6e22e">length</span>(<span style="color:#a6e22e">unique</span>(monisotopic_molecular_weight))<span style="color:#f92672">/</span><span style="color:#a6e22e">length</span>(<span style="color:#a6e22e">unique</span>(smiles))) <span style="color:#f92672">%&gt;%</span>
        <span style="color:#a6e22e">ungroup</span>()
</code></pre></div><pre><code>## # A tibble: 28 x 2
##    super_class                                ratio
##    &lt;chr&gt;                                      &lt;dbl&gt;
##  1 Acetylides                                1.00  
##  2 Alkaloids and derivatives                 0.761 
##  3 Benzenoids                                0.572 
##  4 Homogeneous metal compounds               0.980 
##  5 Homogeneous non-metal compounds           0.972 
##  6 Hydrocarbon derivatives                   0.800 
##  7 Hydrocarbons                              0.456 
##  8 Inorganic compounds                       1.00  
##  9 Lignans, neolignans and related compounds 0.669 
## 10 Lipids and lipid-like molecules           0.0604
## # ... with 18 more rows
</code></pre><p>Well, it&rsquo;s not a uniform distribution. For lipid, the ratio is about 0.06 and MS/MS analysis is required. However, for acetylides, homogeneous metal compounds, homogeneous non-metal compounds, organic polymers, organonitrogen compounds, organohalogen compounds, organic nitrogen compounds, hydrocarbon derivatives, inorganic compounds, mixed metal/non-metal compounds, organic compounds, organic salts, organophosphorus compounds, and organometallic compounds, the ratio is above 0.8. I think it&rsquo;s fine to use MS data to make annotation for those compounds. For other groups with ratio range from 0.23 to 0.8, it&rsquo;s hard to say. Basically, if you removed lipid from your samples in the pretreatment, it&rsquo;s fine to use MS data to check the data. However, when you find lipid, take care and make confirmation by MS/MS.</p>
<h2 id="mass-distribution">Mass distribution</h2>
<p>The mass distribution of all the metabolites is quite different from comment mass spectrum database.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(hmdb<span style="color:#f92672">$</span>monisotopic_molecular_weight,breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-6-1.png" alt="plot of chunk unnamed-chunk-6"></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(<span style="color:#a6e22e">unique</span>(hmdb<span style="color:#f92672">$</span>monisotopic_molecular_weight,breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>))
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-6-2.png" alt="plot of chunk unnamed-chunk-6"></p>
<p>However, we could separate the data set into lipid group and other compounds and check again.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">lipid <span style="color:#f92672">&lt;-</span> hmdb[hmdb<span style="color:#f92672">$</span>super_class <span style="color:#f92672">==</span> <span style="color:#e6db74">&#39;Lipids and lipid-like molecules&#39;</span>,]
other <span style="color:#f92672">&lt;-</span> hmdb[<span style="color:#f92672">!</span>hmdb<span style="color:#f92672">$</span>super_class <span style="color:#f92672">==</span> <span style="color:#e6db74">&#39;Lipids and lipid-like molecules&#39;</span>,]
</code></pre></div><p>91391 compounds are classified into Lipids and lipid-like molecules and dominate 80% of the metabolites in HMDB database. Their mass distribution is here:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(lipid<span style="color:#f92672">$</span>monisotopic_molecular_weight,breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-8-1.png" alt="plot of chunk unnamed-chunk-8"></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(other<span style="color:#f92672">$</span>monisotopic_molecular_weight,breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-8-2.png" alt="plot of chunk unnamed-chunk-8"></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(<span style="color:#a6e22e">unique</span>(lipid<span style="color:#f92672">$</span>monisotopic_molecular_weight),breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-8-3.png" alt="plot of chunk unnamed-chunk-8"></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">hist</span>(<span style="color:#a6e22e">unique</span>(other<span style="color:#f92672">$</span>monisotopic_molecular_weight),breaks <span style="color:#f92672">=</span> <span style="color:#ae81ff">50</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-8-4.png" alt="plot of chunk unnamed-chunk-8"></p>
<p>In this case, I have to say the 0-500 are mainly non-lipid metabolites while 500-1000 are dominated by lipids.</p>
<h2 id="mass-defect-analysis">Mass defect analysis</h2>
<p>For lipid compounds, we expected a mass defect with certain pattern. Here we use -CH2- as an example.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># lipid</span>
mdalipid <span style="color:#f92672">&lt;-</span> enviGCMS<span style="color:#f92672">::</span><span style="color:#a6e22e">getmassdefect</span>(<span style="color:#a6e22e">unique</span>(lipid<span style="color:#f92672">$</span>monisotopic_molecular_weight)<span style="color:#a6e22e">[unique</span>(lipid<span style="color:#f92672">$</span>monisotopic_molecular_weight)<span style="color:#f92672">&lt;</span><span style="color:#ae81ff">1000</span>],<span style="color:#ae81ff">0.9988</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-9-1.png" alt="plot of chunk unnamed-chunk-9"></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e"># other</span>
mdaother <span style="color:#f92672">&lt;-</span> enviGCMS<span style="color:#f92672">::</span><span style="color:#a6e22e">getmassdefect</span>(<span style="color:#a6e22e">unique</span>(other<span style="color:#f92672">$</span>monisotopic_molecular_weight)<span style="color:#a6e22e">[unique</span>(other<span style="color:#f92672">$</span>monisotopic_molecular_weight)<span style="color:#f92672">&lt;</span><span style="color:#ae81ff">1000</span>],<span style="color:#ae81ff">0.9988</span>)
</code></pre></div><p><img src="https://yufree.cn/images/unnamed-chunk-9-2.png" alt="plot of chunk unnamed-chunk-9"></p>
<p>We could find the distribution of mass defect and m/z show different profiles between lipid metabolites and other metabolites. We could use more units to build a model between compounds' class and multiple mass defects. In this case, we might spread one-dimension of data(m/z) into multiple divisions. Then a simple machine learning could give us the answers. I think such way would be a better option compared with build models with thousands of molecular descriptors. When you detected your signal, you know nothing about the structures and such QSPR model would only be useful when you have few candidates.</p>
<h2 id="home-message">Home message</h2>
<ul>
<li>
<p>If you don&rsquo;t perform lipidomics, MS would be enough for annotation. Of course, you still need high resolution.</p>
</li>
<li>
<p>By using multiple mass defect analysis, we might build a model to class unknown compounds.</p>
</li>
</ul>

    </div>
    

<nav id="article-nav">
    
    <a href="https://yufree.cn/en/2018/04/11/play-with-hmdb-datasets/" id="article-nav-older" class="article-nav-link-wrap">
      <div class="article-nav-title"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Play with HMDB datasets: Part I</div>
    </a>
    

    
    <a href="https://yufree.cn/en/2018/07/13/metabolomics-data-analysis-workshop-slides-uwaterloo/" id="article-nav-newer" class="article-nav-link-wrap">
      <div class="article-nav-title">Metabolomics data analysis workshop slides @ UWaterloo <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></div>
    </a>
    
</nav>
<script type="text/javascript">
document.addEventListener('keyup', function(e) {
  if (e.target.nodeName.toUpperCase() != 'BODY') return;
  var url = false;
  if (e.which == 37) {  
    
    url = 'https:\/\/yufree.cn\/en\/2018\/04\/11\/play-with-hmdb-datasets\/';
    
  } else if (e.which == 39) {  
    
    url = 'https:\/\/yufree.cn\/en\/2018\/07\/13\/metabolomics-data-analysis-workshop-slides-uwaterloo\/';
    
  }
  if (url) window.location = url;
});
</script>



  </article>

  <script src="https://giscus.app/client.js"
        data-repo="yufree/yufree.cn"
        data-repo-id="MDEwOlJlcG9zaXRvcnk4NzE0Njc0OA=="
        data-category="General"
        data-category-id="DIC_kwDOBTHA_M4CWUuJ"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>


</main>

      <footer class="footer">
        <ul class="footer-links">
          
          
          <li><a href="https://github.com/yufree"><i class="fa fa-github" aria-hidden="true" title="Github"></i><span class="sr-only">Github</span></a></li>
          <li><a href="https://twitter.com/yu_free"><i class="fa fa-twitter" aria-hidden="true" title="Twitter"></i><span class="sr-only">Twitter</span></a></li>
          <li><a href="http://weibo.com/yufreecas"><i class="fa fa-weibo" aria-hidden="true" title="新浪微博"></i><span class="sr-only">新浪微博</span></a></li>
          
          <li><a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><i class="fa fa-cc" aria-hidden="true" title="Attribution-NonCommercial-ShareAlike 4.0 International"></i><span class="sr-only">Attribution-NonCommercial-ShareAlike 4.0 International</span></a></li>
          <li><a href="/"><i class="fa fa-copyright" aria-hidden="true" title="Copyright"></i> 2023</a></li>
        </ul>
      </footer>
    </div>
    
    <script async src="https://yufree.cn/js/center-img.js"></script>
    
    <script async src="https://yufree.cn/js/fix-footnote.js"></script>
    
    

    



<script src="//cdn.bootcss.com/highlight.js/9.9.0/highlight.min.js"></script>



<script src="//cdn.bootcss.com/highlight.js/9.9.0/languages/r.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.9.0/languages/yaml.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.9.0/languages/tex.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'G-6S0CPNLV6R', 'auto');
	
	ga('send', 'pageview');
}
</script>

  </body>
</html>

