---
title: 自动化机器学习
author: Miao Yu
date: '2022-07-22'
slug: autoML
categories: []
tags: []
---

自动化机器学习（AutoML）大概在四五年前非常火，现在基本熄火进入平稳期与实用期了，是时候回顾下了。

首先，自动化机器学习同样是用来做机器学习的，机器学习适合做的领域自动化机器学习都可以做。这里自动化主要是把调参、变量选择、模型选择、模型集成等传统需要机器学习专家来做的事流程化自动化执行，可以算是程序员自掘职业坟墓的又一成果。

现在很多学科都在谈机器学习，有些是当辅助用，有些是当魔法用，还有些单纯用来要饭忽悠人的。但你去看看高校培养计划会发现虽然很多学科前沿展望里都在鼓吹，培养上基本放羊，全靠学生自学。这样的后果就是同样都是自称做机器学习的，有的是调包流，跑个泰坦尼克幸存者就说懂机器学习，满嘴随机森林支持向量机，走个MNIST敢自称会深度学习。另外一些是y=f(x)流，精于把自己学科问题抽象成一个可训练的模型，然后直接找机器学习专家合作，根本不管模型细节；另一些则是解释流，只对线性模型跟决策树感兴趣，别的都不关心。

毫无意外，自动化机器学习最适合的是第二类人，当然他们最好对基础模型本身原理有感知。但真到预测性问题上就无所谓了，表现最好的一般是多个不同模型集成的。从原理上说，集成学习就是尝试组合不同原理或假设的模型来尽量多的攫取数据中跟预测目标相关的信息。从这个角度上看，单纯依赖某一种模型对于结构复杂问题的信息利用效率都很难高到哪去；而现在流行的深度学习基本就是对原始数据进行各种各样的线性或非线性变换组合，旨在通过各种基础模型的变换组合尽量多的捕集数据中的信息；而更进一步说，类似AlphaFold2这种变形金刚结构的深度学习框架则在编码器阶段融入了学科知识，例如蛋白共源性或氨基酸结合的亲和度，这样在解决具体学科问题上同时包含了通用机器学习模型对信息的穷举与专业生物化学知识来辅助训练，达到了很出色的表现。当然，这种专业知识跟机器学习深度融合的模型就不能指望自动化机器学习了，得从模型构架上重新设计，此处人才到今天都是缺的，现有的基本都进了大厂的研究机构。

对于大多数当前的应用水平使用者而言，其实自动化机器学习是非常好用的工具。应用者日常面对的就是具体的科学问题，将其转为一个可训练的模型然后交给自动化机器学习去训练，最后或者预测或者尝试解释，然后把结果有效告知决策者或公众。其实这里面应用者更多是一个翻译角色，把隐藏在数据中有价值的规律或现象用人话或可视化手段表示出来，所以精力更多在沟通而不是具体技术上，大量时间都在洗数据跟出报告。虽然现在很多深度学习模型在某些领域已经可以做到自动抽取特征了，但面对具体的问题，洗出一个跟问题相关的特征数据还是很难被通用技术代劳的，或者说通用技术效率相对低下。举个例子，要预测污水厂效率，有人会把所有工厂传感数据送进模型，而有经验的人可以直接用跟污水处理相关的技术指标，前后训练用的时间完全不同，后者可以达到实时预测。现在很多人转码农经常是直接把自己专业知识给扔了，其实如果利用得当，其职业前景或岗位不可替代性要比搞通用算法那批人好很多。

其实，自动化机器学习另一个相关议题在于迁移学习。也就是说有很多已经训练好的通用模型可以直接调用或在其构架上定向训练。如果是自然语言处理任务，可以用Open AI GPT系列模型，虽然不开源（开源可以用Bert），但通过调用API一样可以用。图像识别可以拿 ResNet 或 VGG16 来用，这里可以省不少事。这些已经训练好的模型都算是大模型，如果想定向优化到一个小数据集或数据领域里可以特异性去训练其中一层或几层，也可以稍微调下构架在后面补上一两个层来收集数据集中信息，鉴于这些都属于深度学习领域，最好还是先去搞明白最近三五年的一些进展再动手。不过实际研究中数据可能既不是图像也不是文字，没有可直接迁移的通用模型，而且数据量也不大，所以不容易受益于机器学习领域的进展。不过鉴于现在自动化机器学习已经涉及了深度学习，所以自动化训练一个模型问题也不大。

从应用角度，自动化机器学习模型很容易构建，基本上你只需要明确目标跟预测变量就可以了。机器学习领域最喜欢折腾的是自然语言跟图片的分类、识别等问题，但应用领域更常见的数据类型是表格或者说样本-特征矩阵，当然有些特征是明确的量化值，有的则可能也是图片、语音等数据。举个例子，我想知道一个人是否得呼吸道疾病，那么我可以收集其流行病学调查问卷数据，也可以收集其体检的胸片，还可以收集其读某段文字的发音数据等。这里任何单一来源数据都可以单独构建一个预测模型，然后你可以做个集成学习；另一个思路则是把每个来源的数据都看成一组特征，将所有特征转化整合在一张数据表里去预测。这里很难说哪种思路效果更好，这里只需要解决非结构化数据（语音、图像、文字等）的特征提取两者在本质上就是一回事了，不过眼下还是要区分下结构化数据跟非结构化数据模型好一些，两者模型构建逻辑上还是区别很大的。

下面我们来个实战，看看这个操作有多简单。这里我用到的是H2O的AutoML这个框架。

```{r}
# 读取一个代谢组学示例数据，x是所有的特征峰，y是肺癌与否
download.file('https://github.com/yufree/rmwf/raw/master/inst/demodata/untarget/MTBLS28posmzrt.csv','pos.csv')
mzrt <- enviGCMS::getmzrtcsv('pos.csv')
lv <- ifelse(grepl('Control',mzrt$group$sample_group),'control','case')
trainIndex <- sample(1:1005,700)
train <- mzrt$data[, trainIndex]
train <- cbind.data.frame(Y=lv[trainIndex],t(train))
test  <- mzrt$data[,-trainIndex]
test  <- cbind.data.frame(Y=lv[-trainIndex],t(test))
y = 'Y'
pred = setdiff(names(train), y)
#convert variables to factors
train[,y] = as.factor(train[,y])
test[,y] = as.factor(test[,y])
library(h2o)
h2o.init()
train_h = as.h2o(train)
test_h = as.h2o(test)
# Run AutoML for 20 base models
aml = h2o.automl(x = pred, y = y,
                  training_frame = train_h,
                  max_models = 10,
                  seed = 42
                 )
# AutoML Leaderboard
lb <- h2o.get_leaderboard(object = aml, extra_columns = "ALL")
lb
# prediction
pred <- h2o.predict(aml,test_h[,-1])
caret::confusionMatrix(test$Y, as.data.frame(pred)$predict)
# explain the model
h2o.explain(aml, test_h)
# plot M264.1215T23.3
boxplot(test$M264.1215T23.3~test$Y,xlab='',ylab='response')
h2o.shutdown(prompt = F)
```

从上面例子可以看出，一个完整的自动化机器学习要包括下面几个步骤：

- 读入数据并至少拆分为训练集与检验集
- 在训练集上进行自动化机器学习
- 检查预测模型的表现
- 在检验集上观察预测效果
- 解释模型

这里我们观察到检验集上模型表现弱于训练集，存在过拟合，可考虑调整下交叉检验的参数。当然现在自动训练的模型表现比我一年多前用随机森林做同样数据的[演示](https://yufree.cn/cn/2021/03/07/demo-ml-metabolomics/)效果还差一点，但差距并不大可接受。关键在于上面那段代码的可移植性要比单纯针对某个模型要好很多，科研中引入机器学习更多是做探索，有段随时可测的代码会让整个流程更顺畅。

这里另一个相关主题是可解释性机器学习。我们做研究的预测率高几个百分点意义不大，但要是能说出哪个变量对预测的贡献高低并展示出来就很有意义了。这方面全局影响可以用Partial Dependence Plot（PDP） 来表示，或者给出变量重要性，或者给出 SHAP 贡献值，这里面 PDP 是针对全局预测的，还有些其他的例如 LIME 可以对单一预测给出变量重要性，具体怎么用需要结合你的科学问题来探索。

总之，我认为当前自动化机器学习对实际科研问题已经是一种可以用的水平了，可以快速试错一些想法找一些方向。当然，你最好是明白自己在干什么。

