on:
  push:
    branches: [main, master]
name: blogdown
jobs:
  blogdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("blogdown"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.79.1")'
      - name: Install Hugo theme
        run: Rscript -e 'blogdown::install_theme("yufree/hugo-lithium-theme")'
      - name: Build site
        run: blogdown:::build_site(TRUE)
        shell: Rscript {0} 
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: public