on:
  push:
    branches: [main, master]

name: blogdown
jobs:
  blogdown:
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
      - name: install blogdown
        run: |
          R -e 'install.packages("blogdown")'
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo()'
      - name: Build site
        run: |
          R -e 'blogdown::build_site(TRUE)'
      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
